# Generated by Django 6.0.2 on 2026-02-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('BC', 'Bem Conservada'), ('MBC', 'Muito Bem Conservada'), ('SOB', 'Soberba'), ('FC', 'Flor de Cunho'), ('UNC', 'Uncirculated')], max_length=3)),
                ('quantity', models.IntegerField(default=1)),
                ('acquired_at', models.DateField(blank=True, null=True)),
                ('cost_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_value_brl', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estimated_at', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coin_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.cointype')),
            ],
        ),
    ]
