# Generated by Django 6.0.2 on 2026-02-22 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='coinitem',
            name='origin',
            field=models.CharField(choices=[('compra', 'Compra'), ('doacao', 'Doação'), ('troca', 'Troca'), ('outro', 'Outro')], default='compra', max_length=10),
        ),
        migrations.AddField(
            model_name='coinitem',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donated_items', to='collection.donor'),
        ),
    ]
