# Generated by Django 6.0.2 on 2026-02-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_donor_coinitem_origin_coinitem_donor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinitem',
            name='origin',
            field=models.CharField(choices=[('compra', 'Compra'), ('doacao', 'Doação'), ('troca', 'Troca'), ('outro', 'Outro')], default='outro', max_length=10),
        ),
    ]
