# Generated by Django 6.0.2 on 2026-02-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('description', models.TextField()),
                ('sources', models.TextField(blank=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_contexts', to='catalog.country')),
            ],
        ),
        migrations.CreateModel(
            name='CoinTypeContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(max_length=100)),
                ('coin_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contexts', to='catalog.cointype')),
                ('context', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coin_types', to='history.historicalcontext')),
            ],
        ),
    ]
