# Generated by Django 6.0.2 on 2026-02-21 23:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('iso2', models.CharField(max_length=2)),
                ('iso3', models.CharField(max_length=3, unique=True)),
                ('capital', models.CharField(blank=True, max_length=100)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('currency_name', models.CharField(blank=True, max_length=100)),
                ('currency_symbol', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('subregion', models.CharField(blank=True, max_length=100)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezones_raw', models.TextField(blank=True)),
                ('wikidata_id', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CoinType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denomination', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('material', models.CharField(max_length=100)),
                ('diameter_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('weight_g', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('mintage', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coin_types', to='catalog.country')),
            ],
            options={
                'ordering': ['country', 'year', 'denomination'],
                'unique_together': {('country', 'denomination', 'year')},
            },
        ),
    ]
