# Generated by Django 6.0.2 on 2026-02-22 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointype',
            name='material',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
