# Generated by Django 6.0.2 on 2026-02-22 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_cointype_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointype',
            name='deleted_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
    ]
